In [1]:
import torch
import torch.nn.functional as F

# 假设 data 是你的数据，转换为 PyTorch 的 Tensor 类型
# data = torch.tensor([10.0, 2.0, 3.0, 4.0, 0.50])
# data = torch.tensor([0.10, 0.12, 0.13, 0.14, 0.15])
data = torch.tensor([0.10, 12, 13, 14, 0.15])

# 使用 normalize 函数进行归一化
normalized_data = F.normalize(data, p=2, dim=0)

print("原始数据：", data)
print("归一化后的数据：", normalized_data)

std = torch.std(data)
std

原始数据： tensor([ 0.1000, 12.0000, 13.0000, 14.0000,  0.1500])
归一化后的数据： tensor([0.0044, 0.5319, 0.5762, 0.6205, 0.0066])


tensor(7.0873)

In [2]:
import torch
mean = torch.mean(data)
print(mean)
data2 = 1-normalized_data
print(F.softmax(data2))
ss = 1/std
print(ss)
F.softmax(data2/ss)

tensor(7.8500)
tensor([0.2708, 0.1598, 0.1529, 0.1463, 0.2702])
tensor(0.1411)


C:\Users\maowenjie\AppData\Local\Temp\ipykernel_63860\2827201732.py:5: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(F.softmax(data2))
C:\Users\maowenjie\AppData\Local\Temp\ipykernel_63860\2827201732.py:8: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  F.softmax(data2/ss)


tensor([0.4906, 0.0117, 0.0085, 0.0062, 0.4830])

In [3]:
std_ = F.sigmoid(ss)
F.softmax(data/std_, dim=0)

tensor([4.4647e-12, 2.0226e-02, 1.3102e-01, 8.4875e-01, 4.9019e-12])

In [3]:
import torch
torch.randn([10 // 2, 4]) * 1

tensor([[ 0.3067, -0.3329,  2.0159,  0.2786],
        [-0.4695, -0.3429,  3.0043, -0.6751],
        [-1.6438,  1.4289,  0.7270, -0.1601],
        [-0.9893, -2.4254,  0.8428,  1.8022],
        [ 0.7588,  0.0626, -0.6226, -0.3350]])